name: "Solidxpress"
description: "Solidxpress"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: /blog/:year/:month/:day/:title

navigation:
    - text: dashboard
      url: /dashboard
      icon: dashboard.svg
    - text: branches
      url: /branches
      icon: branches.svg
    - text: contents
      url: /contents
      icon: content.svg 
    - text: beacons
      url: /beacons 
      icon: beacons.svg
    - text: customers
      url: /customers
      icon: buddy.svg
    

